server:
  port: 8002

spring:
  application:
    name: usermanaging

eureka:
  instance:
    prefer-ip-address: true
    instance-id: localhost:8002
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka